function pts = generatePaddlerLoads()
           
Wm  = 200 * 1.1;    % assume 200 lbs for male paddler, * 1.1 FOS for variance
Wf  = 160 * 1.1;          

% Positions
x_2p   = [ +7.5*12,  -7.5*12 ];     % +-5.0 ft
x_4p_i = [ +3*12,  -3*12 ];     % inner +-3.0 ft  female paddlers
x_4p_o = [ +5.5*12,-5.5*12 ];   % outer +-5.5 ft  male paddlers
x_3p_i = [ 0 ]; % inner female paddler
x_3p_o = [4.5*12 -4.5*12 ]; % outer male paddlers
% Load case arrays
case_2M = [ x_2p(:),   -Wm*ones(numel(x_2p),1) ]; % male tandem
case_2F = [ x_2p(:),   -Wf*ones(numel(x_2p),1) ]; % female tandem
case_4  = [ x_4p_i(:), -Wf*ones(numel(x_4p_i),1) ;   % coed
            x_4p_o(:), -Wm*ones(numel(x_4p_o),1) ]; 
case_3  = [ x_3p_i(:), -Wf*ones(numel(x_3p_i),1) ;
            x_3p_o(:), -Wm*ones(numel(x_3p_o),1) ];
case_null = [ 0, 0 ];

pts = struct( ...
      'case_2M',      case_2M,  ...
      'case_2F',      case_2F,  ...
       'case_4',       case_4,  ...
       'case_3',       case_3,  ...
    'case_null',    case_null,  ...
    'meta', struct( ...
        'weights_lbf', struct('male',Wm,'female',Wf), ...
        'sign_convention','downward negative', ...
        'positions_in', struct('two_paddlers',x_2p,'inner_two',x_4p_i,'outer_two',x_4p_o) ...
    ) ...
);
end
